pipeline {
    agent any

    options {
        timestamps()
    }

    environment {
        TF_IN_AUTOMATION = "true"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform init/validate/plan') {
            steps {
                withCredentials([string(credentialsID: 'AZURE_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                                 string(credentialsID: 'AZURE_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                                 string(credentialsID: 'AZURE_TENANT_ID', variable: 'ARM_TENANT_ID'),
                                 string(credentialsID: 'AZURE_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID')]) 
                                 {
                                    bat '''
                                        terraform --version
                                        terraform init
                                        terraform validate
                                        terraform plan -out=tfplan
                                    '''
                                 }
            }
        }
        stage('Manual Approval') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: 'Proceed with Terraform Apply (Creare Resource Group)?'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                withCredentials([string(credentialsID: 'AZURE_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                                 string(credentialsID: 'AZURE_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                                 string(credentialsID: 'AZURE_TENANT_ID', variable: 'ARM_TENANT_ID'),
                                 string(credentialsID: 'AZURE_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID')]) 
                                 {
                                    bat '''
                                        terraform apply -auto-approve tfplan
                                        terraform output
                                    '''
                                 }
            }
        }
}

}
