pipeline {
    agent any

    environment {
        TF_IN_AUTOMATION = "true"
        tf_input = "false"
        TF_BIN = "C:/Terraform/terraform.exe"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform init/validate/plan') {
            steps {
                dir('az-VNet') {
                    withCredentials([string(credentialsId: 'AZURE_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                                     string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                                     string(credentialsId: 'AZURE_TENANT_ID', variable: 'ARM_TENANT_ID'),
                                     string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID')]) {
                       bat '''
                            "%TF_BIN%" --version
                            "%TF_BIN%" init -input=false -no-color
                            "%TF_BIN%" validate -no-color
                            "%TF_BIN%" plan -out=tfplan -no-color
                        '''
                    }
                }
            }
        }
    stage('Manual Approval') {
            steps {
                timeout(time: 10, unit: 'MINUTES') {
                    input message: 'Proceed with Terraform Apply (Create VNet and Subnet)?'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir('az-VNet') {
                    withCredentials([string(credentialsId: 'AZURE_CLIENT_ID', variable: 'ARM_CLIENT_ID'),
                                     string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'ARM_CLIENT_SECRET'),
                                     string(credentialsId: 'AZURE_TENANT_ID', variable: 'ARM_TENANT_ID'),
                                     string(credentialsId: 'AZURE_SUBSCRIPTION_ID', variable: 'ARM_SUBSCRIPTION_ID')]) {
                        bat '''
                            "%TF_BIN%" apply -auto-approve tfplan -no-color
                            if %ERRORLEVEL% NEQ 0 exit /b %ERRORLEVEL%
                            "%TF_BIN%" output -no-color -json
                        '''
                    }
                }
            }
        }
    }
}
